repos:
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.2
    hooks:
      - id: go-fmt-import
        exclude: ".*.pb.go"
      - id: go-vet
      - id: go-unit-tests
      - id: go-err-check
        exclude: ".*_gen.go"
      - id: go-static-check
        exclude: "scripts/.*"
