// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: _examples/python/tasks/tasks.proto

package tasks

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MainTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *MainTask) Reset() {
	*x = MainTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file___examples_python_tasks_tasks_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MainTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MainTask) ProtoMessage() {}

func (x *MainTask) ProtoReflect() protoreflect.Message {
	mi := &file___examples_python_tasks_tasks_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MainTask.ProtoReflect.Descriptor instead.
func (*MainTask) Descriptor() ([]byte, []int) {
	return file___examples_python_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *MainTask) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type ChildTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *ChildTask) Reset() {
	*x = ChildTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file___examples_python_tasks_tasks_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChildTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChildTask) ProtoMessage() {}

func (x *ChildTask) ProtoReflect() protoreflect.Message {
	mi := &file___examples_python_tasks_tasks_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChildTask.ProtoReflect.Descriptor instead.
func (*ChildTask) Descriptor() ([]byte, []int) {
	return file___examples_python_tasks_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *ChildTask) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type OnCompleteTask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *OnCompleteTask) Reset() {
	*x = OnCompleteTask{}
	if protoimpl.UnsafeEnabled {
		mi := &file___examples_python_tasks_tasks_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnCompleteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCompleteTask) ProtoMessage() {}

func (x *OnCompleteTask) ProtoReflect() protoreflect.Message {
	mi := &file___examples_python_tasks_tasks_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCompleteTask.ProtoReflect.Descriptor instead.
func (*OnCompleteTask) Descriptor() ([]byte, []int) {
	return file___examples_python_tasks_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *OnCompleteTask) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File___examples_python_tasks_tasks_proto protoreflect.FileDescriptor

var file___examples_python_tasks_tasks_proto_rawDesc = []byte{
	0x0a, 0x22, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x70, 0x79, 0x74, 0x68,
	0x6f, 0x6e, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x1c, 0x0a, 0x08, 0x4d,
	0x61, 0x69, 0x6e, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x1d, 0x0a, 0x09, 0x43, 0x68, 0x69,
	0x6c, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x22, 0x0a, 0x0e, 0x4f, 0x6e, 0x43, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x42, 0x30, 0x5a, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a, 0x70, 0x6f, 0x7a, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x6a, 0x6f, 0x62, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x73, 0x2f, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file___examples_python_tasks_tasks_proto_rawDescOnce sync.Once
	file___examples_python_tasks_tasks_proto_rawDescData = file___examples_python_tasks_tasks_proto_rawDesc
)

func file___examples_python_tasks_tasks_proto_rawDescGZIP() []byte {
	file___examples_python_tasks_tasks_proto_rawDescOnce.Do(func() {
		file___examples_python_tasks_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(file___examples_python_tasks_tasks_proto_rawDescData)
	})
	return file___examples_python_tasks_tasks_proto_rawDescData
}

var file___examples_python_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file___examples_python_tasks_tasks_proto_goTypes = []interface{}{
	(*MainTask)(nil),       // 0: tasks.MainTask
	(*ChildTask)(nil),      // 1: tasks.ChildTask
	(*OnCompleteTask)(nil), // 2: tasks.OnCompleteTask
}
var file___examples_python_tasks_tasks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file___examples_python_tasks_tasks_proto_init() }
func file___examples_python_tasks_tasks_proto_init() {
	if File___examples_python_tasks_tasks_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file___examples_python_tasks_tasks_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MainTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___examples_python_tasks_tasks_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChildTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file___examples_python_tasks_tasks_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnCompleteTask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file___examples_python_tasks_tasks_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file___examples_python_tasks_tasks_proto_goTypes,
		DependencyIndexes: file___examples_python_tasks_tasks_proto_depIdxs,
		MessageInfos:      file___examples_python_tasks_tasks_proto_msgTypes,
	}.Build()
	File___examples_python_tasks_tasks_proto = out.File
	file___examples_python_tasks_tasks_proto_rawDesc = nil
	file___examples_python_tasks_tasks_proto_goTypes = nil
	file___examples_python_tasks_tasks_proto_depIdxs = nil
}
